access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH:access-refresh-token-keys/access-token.key}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH:access-refresh-token-keys/access-token.pub}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH:access-refresh-token-keys/refresh-token.key}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH:access-refresh-token-keys/refresh-token.pub}
spring:
  main:
    allow-circular-references: true
  application:
    name: PafBackend
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://cooking-app-user:ranidu123@cooking-app-cluster.6f2l0rg.mongodb.net/?retryWrites=true&w=majority&appName=cooking-app-cluster
      database: ${MONGODB_DB:myFirstDatabase}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23litdBMIIe0YQNmOn
            client-secret: bd93c525884141aa7af972a79c99f76681adbd87
          google:
            client-id: 791314813736-eoti9ailj9ou93kvq17lu0m0o08rgfna.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    org.springframework.security: DEBUG
file:
  upload-dir: uploads